Added dockerfile for neon distro.
Wenzel/docker-kdesrc-build pull request #20
Opened 2018-07-29 10:35 UTC by carlonluca

2018-07-29 11:17 UTC, Wenzel requested changes

2018-07-29 11:17 UTC, Wenzel commented on Dockerfile-neon
> +			python3-twisted && \
you have tabs instead of spaces here

2018-07-31 05:21 UTC, carlonluca commented
Should be ok now.

2018-07-31 09:38 UTC, Wenzel approved these changes

2018-07-31 09:38 UTC, merged